### ISSUE TITLE
Vagrant Up - problems with installation

### ISSUE THREAD

**Issue by mredigonda** [omegaup/deploy#14]
```
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Clearing any previously set forwarded ports...
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 80 (guest) => 8080 (host) (adapter 1)
    default: 21680 (guest) => 21680 (host) (adapter 1)
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: 
    default: Vagrant insecure key detected. Vagrant will automatically replace
    default: this with a newly generated keypair for better security.
    default: 
    default: Inserting generated public key within guest...
    default: Removing insecure key from the guest if it's present...
    default: Key inserted! Disconnecting and reconnecting using new SSH key...
==> default: Machine booted and ready!
==> default: Checking for guest additions in VM...
    default: The guest additions on this VM do not match the installed version of
    default: VirtualBox! In most cases this is fine, but in rare cases it can
    default: prevent things such as shared folders from working properly. If you see
    default: shared folder errors, please make sure the guest additions within the
    default: virtual machine match the version of VirtualBox you have installed on
    default: your host and reload your VM.
    default: 
    default: Guest Additions Version: 5.0.40
    default: VirtualBox Version: 5.2
==> default: Mounting shared folders...
    default: /vagrant => /home/maxi/Documentos/Programming/deploy
    default: /opt/omegaup => /home/maxi/Documentos/Programming/deploy/omegaup
==> default: Running provisioner: shell...
    default: Running: /tmp/vagrant-shell20180219-8242-sdtd1t.sh
    default: dpkg-query: no packages found matching puppet-common
    default: dpkg-query: no packages found matching ruby
    default: WARNING: 
    default: apt
    default:  
    default: does not have a stable CLI interface. 
    default: Use with caution in scripts.
    default: Reading package lists...
    default: E
    default: : 
    default: Could not get lock /var/lib/apt/lists/lock - open (11: Resource temporarily unavailable)
    default: E
    default: : 
    default: Unable to lock directory /var/lib/apt/lists/
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```
This was the output, I received when using `vagrant up` the last time.
I still haven't learned a lot about Vagrant to interpret this output, but I decided to share this here since it can be useful to future contributors.
Sorry for not providing reproduction steps, I don't have continuous access to this computer, but eventually I can get more information about it if you ask for it.

**Comment by AtharvaKhare** [comment]
Maybe retry with ```vagrant reload --provision```? The cloud images haven't changed since 5 days, so I do not think that is the problem.

I do not know shell script well, but if above step does not work, edit ```linux-install.sh``` and add ```sleep 1m``` after ```set -e```, and try again?

**Comment by lhchavez** [comment]
This is most likely the issue, since it will prevent a lot of stuff from working correctly:

    default: The guest additions on this VM do not match the installed version of
    default: VirtualBox! In most cases this is fine, but in rare cases it can
    default: prevent things such as shared folders from working properly. If you see
    default: shared folder errors, please make sure the guest additions within the
    default: virtual machine match the version of VirtualBox you have installed on
    default: your host and reload your VM.

you can try to manually update the guest additions by following something like https://www.techrepublic.com/article/how-to-install-virtualbox-guest-additions-on-a-gui-less-ubuntu-server-host/

Once that's done, try running the command that @AtharvaKhare suggested and in theory everything should work.

**Comment by mredigonda** [comment]
Great, I'll try this when I get physical access to this computer again, thank you.

**Comment by mustafa-jalal** [comment]
Hi , how to download and install omega up script ??

**Comment by sagban** [comment]
Then after we have to make change sin this repo
[https://github.com/omegaup/omegaup](https://github.com/omegaup/omegaup) right?
