### ISSUE TITLE
Issue with installation

### ISSUE THREAD

**Issue by prondubuisi** [omegaup/deploy#18]
Hello @lhchavez I tried deploying Omegaup locally and `vagrant Up ` is done with some errors, I have also ran `vagrant up --provision` and `vagrant provision` with errors. Here is a link with the error details https://pastebin.com/K03AFPG1. When i navigate to http://localhost:8080/ i do see the omegaup site though.
![screenshot from 2018-12-05 07-37-28](https://user-images.githubusercontent.com/22311928/49494657-a98dee00-f860-11e8-9c5d-633a92c5c97b.png)

**Comment by lhchavez** [comment]
everything is working correctly! :D you do need to run the command in the error box (and let it keep running sonit automatically detects changes in JavaScript files that are modofied and need recompilation).
