### ISSUE TITLE
Error al usar Vagrant Up

### ISSUE THREAD

**Issue by samdsmx** [omegaup/deploy#3]
Al finalizar manda el siguiente mensaje: 

The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong. Envio Log de consola
[log.txt](https://github.com/omegaup/deploy/files/176973/log.txt)

Al ingresar al aplicativo me despliega el mensaje No Config file. Envío pantalla
![noconfigfile](https://cloud.githubusercontent.com/assets/5838427/13830324/8178a6fa-eb91-11e5-9bd9-e6db2f9d89a6.png)

**Comment by joemmanuel** [comment]
"vagrant up" debe general muchos mensajes en consola. Puedes mandarnos todo
eso?

On Wed, Mar 16, 2016 at 3:10 PM, Sergo Márquez <notifications@github.com>
wrote:

> Al finalizar manda el siguiente mensaje:
>
> The SSH command responded with a non-zero exit status. Vagrant
> assumes that this means the command failed. The output for this command
> should be in the log above. Please read the output to determine what
> went wrong. Envio Log de consola
> log.txt <https://github.com/omegaup/deploy/files/176973/log.txt>
>
> Al ingresar al aplicativo me despliega el mensaje No Config file. Envío
> pantalla
> [image: noconfigfile]
> <https://cloud.githubusercontent.com/assets/5838427/13830324/8178a6fa-eb91-11e5-9bd9-e6db2f9d89a6.png>
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/omegaup/deploy/issues/3>
>



-- 
Saludos,
Joemmanuel Ponce

**Comment by samdsmx** [comment]
Esta en el adjunto. 
[log.txt](https://github.com/omegaup/deploy/files/176982/log.txt)

**Comment by alanboy** [comment]
```
==> default: Notice: /Stage[main]/Omegaup/Omegaup::Config_php[/opt/omegaup/frontend/server/config.php]/File[/opt/omegaup/frontend/server/config.php]: Dependency Vcsrepo[/opt/omegaup] has failures: true
==> default: Warning: /Stage[main]/Omegaup/Omegaup::Config_php[/opt/omegaup/frontend/server/config.php]/File[/opt/omegaup/frontend/server/config.php]: Skipping because of failed dependencies
```
hmmm

`Skipping because of failed dependencies`

la dependencia que fallo es esta al parecer:

```
==> default: Error: Execution of '/usr/bin/apt-get -q -y -o DPkg::Options::=--force-confold install phpcs' returned 100: Reading package lists...
==> default: Building dependency tree...
==> default: Reading state information...
==> default: E: Unable to locate package phpcs
==> default: Error: /Stage[main]/Omegaup::Developer_environment/Package[phpcs]/ensure: change from purged to present failed: Execution of '/usr/bin/apt-get -q -y -o DPkg::Options::=--force-confold install phpcs' returned 100: Reading package lists...
==> default: Building dependency tree...
==> default: Reading state information...
==> default: E: Unable to locate package phpcs
```

**Comment by samdsmx** [comment]
#

**Comment by joemmanuel** [comment]
Seguramente omegaup localhost no va a funcionar al 100% por el drift entre
los bd.sql... alguien puede actualizarlos?

On Wed, Mar 16, 2016 at 7:06 PM, lhchavez <notifications@github.com> wrote:

> Closed #3 <https://github.com/omegaup/deploy/issues/3> via omegaup/puppet@
> dba21f9
> <https://github.com/omegaup/puppet/commit/dba21f97a9f2d71fae28ed75f2d98f3e0fd95a51>
> .
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/omegaup/deploy/issues/3#event-592789253>
>



-- 
Saludos,
Joemmanuel Ponce

**Comment by samdsmx** [comment]
`Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'omegaup-vivid'...
==> default: Matching MAC address for NAT networking...
==> default: Setting the name of the VM: deploy-master_default_1458181379517_45324
==> default: Clearing any previously set forwarded ports...
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 80 (guest) => 8080 (host) (adapter 1)
    default: 21680 (guest) => 21680 (host) (adapter 1)
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: Warning: Remote connection disconnect. Retrying...
    default:
    default: Vagrant insecure key detected. Vagrant will automatically replace
    default: this with a newly generated keypair for better security.
    default:
    default: Inserting generated public key within guest...
    default: Removing insecure key from the guest if it's present...
    default: Key inserted! Disconnecting and reconnecting using new SSH key...
==> default: Machine booted and ready!
==> default: Checking for guest additions in VM...
    default: The guest additions on this VM do not match the installed version of
    default: VirtualBox! In most cases this is fine, but in rare cases it can
    default: prevent things such as shared folders from working properly. If you see
    default: shared folder errors, please make sure the guest additions within the
    default: virtual machine match the version of VirtualBox you have installed on
    default: your host and reload your VM.
    default:
    default: Guest Additions Version: 4.3.36
    default: VirtualBox Version: 5.0
==> default: Mounting shared folders...
    default: /vagrant => D:/Proyectos/omega/deploy-master
    default: /tmp/vagrant-puppet/manifests-846018e2aa141a5eb79a64b4015fc5f3 => D:/Proyectos/omega/deploy-master/puppet/manifests
==> default: Running provisioner: shell...
    default: Running: inline script
==> default: stdin: is not a tty
==> default: Notice: Preparing to install into /etc/puppet/modules ...
==> default: Notice: Downloading from https://forgeapi.puppetlabs.com ...
==> default: Notice: Installing -- do not interrupt ...
==> default: /etc/puppet/modules
==> default: └── puppetlabs-concat (v2.1.0)
==> default: Notice: Preparing to install into /etc/puppet/modules ...
==> default: Notice: Downloading from https://forgeapi.puppetlabs.com ...
==> default: Notice: Installing -- do not interrupt ...
==> default: /etc/puppet/modules
==> default: └── puppetlabs-stdlib (v4.11.0)
==> default: Notice: Preparing to install into /etc/puppet/modules ...
==> default: Notice: Downloading from https://forgeapi.puppetlabs.com ...
==> default: Notice: Installing -- do not interrupt ...
==> default: /etc/puppet/modules
==> default: └── puppetlabs-mysql (v3.7.0)
==> default: Notice: Preparing to install into /etc/puppet/modules ...
==> default: Notice: Downloading from https://forgeapi.puppetlabs.com ...
==> default: Notice: Installing -- do not interrupt ...
==> default: /etc/puppet/modules
==> default: └── puppetlabs-vcsrepo (v1.3.2)
==> default: Notice: Preparing to install into /etc/puppet/modules ...
==> default: Notice: Downloading from https://forgeapi.puppetlabs.com ...
==> default: Notice: Installing -- do not interrupt ...
==> default: /etc/puppet/modules
==> default: └── puppetlabs-apt (v2.2.2)
==> default: Notice: Preparing to install into /etc/puppet/modules ...
==> default: Notice: Downloading from https://forgeapi.puppetlabs.com ...
==> default: Notice: Installing -- do not interrupt ...
==> default: /etc/puppet/modules
==> default: └── jfryman-nginx (v0.3.0)
==> default: Cloning into '/etc/puppet/modules/omegaup'...
==> default: Running provisioner: puppet...
==> default: Running Puppet with omegaup.pp...
==> default: stdin: is not a tty
==> default: Warning: Config file /etc/puppet/hiera.yaml not found, using Hiera defaults
==> default: Warning: Scope(Concat::Fragment[omegaup-500-bee8a28872591beb7bb88847301c4be7]): The $ensure parameter to concat::fragment is deprecated and has no
effect.
==> default: Warning: Scope(Concat::Fragment[omegaup-500-a7f6ce6089afe563cc3e150685efff66]): The $ensure parameter to concat::fragment is deprecated and has no
effect.
==> default: Warning: Scope(Concat::Fragment[omegaup-500-6666cd76f96956469e7be39d750cc7d9]): The $ensure parameter to concat::fragment is deprecated and has no
effect.
==> default: Notice: Compiled catalog for vagrant-ubuntu-vivid-64 in environment production in 1.47 seconds
==> default: Notice: /Stage[main]/Omegaup::Java/Package[openjdk-8-jre]/ensure: ensure changed 'purged' to 'present'
==> default: Notice: /Stage[main]/Omegaup::Directories/File[/var/lib/omegaup]/ensure: created
==> default: Notice: /Stage[main]/Omegaup::Directories/File[/var/log/omegaup]/ensure: created
==> default: Notice: /Stage[main]/Omegaup::Certmanager/File[/usr/bin/certmanager]/ensure: defined content as '{md5}0869d006aef39c56ef9beb6127098cf0'
==> default: Notice: /Stage[main]/Omegaup::Certmanager/File[/etc/certmanager]/ensure: created
==> default: Notice: /Stage[main]/Omegaup::Apt_sources/Apt::Source[hhvm]/Apt::Key[Add key: 0x36aef64d0207e7eee352d4875a16e7281be7a449 from Apt::Source hhvm]/Apt
_key[Add key: 0x36aef64d0207e7eee352d4875a16e7281be7a449 from Apt::Source hhvm]/ensure: created
==> default: Notice: /Stage[main]/Omegaup::Certmanager/Exec[certmanager-ca]/returns: executed successfully
==> default: Notice: /Stage[main]/Omegaup::Database/File[/tmp/omegaup.sql]/ensure: defined content as '{md5}1fc352951188275166edd6b1f296ad1b'
==> default: Notice: /Stage[main]/Omegaup::Database/File[/tmp/omegaup-test-data.sql]/ensure: defined content as '{md5}b6aaaa9e248961e8265ddc50612a9ab8'
==> default: Notice: /Stage[main]/Main/File[/etc/omegaup]/ensure: created
==> default: Notice: /Stage[main]/Omegaup::Users/User[omegaup]/ensure: created
==> default: Notice: /Stage[main]/Mysql::Server::Install/Package[mysql-server]/ensure: ensure changed 'purged' to 'present'
==> default: Notice: /Stage[main]/Mysql::Server::Config/File[mysql-config-file]/ensure: defined content as '{md5}44e7aa974ab98260d7d013a2087f1c77'
==> default: Notice: /Stage[main]/Omegaup::Minijail/File[/etc/sudoers.d/minijail]/ensure: defined content as '{md5}ca23528358bd776d20e3b5ce52c0f50a'
==> default: Notice: /Stage[main]/Main/File[/etc/omegaup/frontend]/ensure: created
==> default: Notice: /Stage[main]/Main/Omegaup::Certmanager::Cert[/etc/omegaup/frontend/certificate.pem]/Exec[certmanager-/etc/omegaup/frontend/certificate.pem]
/returns: executed successfully
==> default: Notice: /Stage[main]/Main/Omegaup::Certmanager::Cert[/etc/omegaup/frontend/certificate.pem]/File[/etc/omegaup/frontend/certificate.pem]/owner: owne
r changed 'root' to 'www-data'
==> default: Notice: /Stage[main]/Main/Omegaup::Certmanager::Cert[/etc/omegaup/frontend/certificate.pem]/File[/etc/omegaup/frontend/certificate.pem]/mode: mode
changed '0644' to '0600'
==> default: Notice: /Stage[main]/Omegaup::Apt_sources/Apt::Source[hhvm]/Apt::Setting[list-hhvm]/File[/etc/apt/sources.list.d/hhvm.list]/ensure: created
==> default: Notice: /Stage[main]/Omegaup::Apt_sources/Apt::Pin[vivid]/Apt::Setting[pref-vivid]/File[/etc/apt/preferences.d/vivid.pref]/ensure: created
==> default: Notice: /Stage[main]/Nginx::Package::Debian/Package[nginx]/ensure: ensure changed 'purged' to 'present'
==> default: Notice: /Stage[main]/Nginx::Config/File[/var/nginx]/ensure: created
==> default: Notice: /Stage[main]/Nginx::Config/File[/var/nginx/client_body_temp]/ensure: created
==> default: Notice: /Stage[main]/Nginx::Config/File[/var/log/nginx]/owner: owner changed 'www-data' to 'root'
==> default: Notice: /Stage[main]/Nginx::Config/File[/var/log/nginx]/group: group changed 'adm' to 'root'
==> default: Notice: /Stage[main]/Nginx::Config/File[/var/log/nginx]/mode: mode changed '0750' to '0755'
==> default: Notice: /Stage[main]/Nginx::Config/File[/var/nginx/proxy_temp]/ensure: created
==> default: Notice: /Stage[main]/Apt/Apt::Setting[conf-update-stamp]/File[/etc/apt/apt.conf.d/15update-stamp]/content: content changed '{md5}b9de0ac9e2c9854b1b
b213e362dc4e41' to '{md5}0962d70c4ec78bbfa6f3544ae0c41974'
==> default: Notice: /Stage[main]/Main/File[/etc/omegaup/grader]/ensure: created
==> default: Notice: /Stage[main]/Main/Omegaup::Certmanager::Cert[/etc/omegaup/grader/keystore.jks]/Exec[certmanager-/etc/omegaup/grader/keystore.jks]/returns:
executed successfully
==> default: Notice: /Stage[main]/Main/Omegaup::Certmanager::Cert[/etc/omegaup/grader/keystore.jks]/File[/etc/omegaup/grader/keystore.jks]/owner: owner changed
'root' to 'omegaup'
==> default: Notice: /Stage[main]/Main/Omegaup::Certmanager::Cert[/etc/omegaup/grader/keystore.jks]/File[/etc/omegaup/grader/keystore.jks]/mode: mode changed '0
644' to '0600'
==> default: Notice: /Stage[main]/Nginx::Config/File[/etc/nginx/nginx.conf]/content: content changed '{md5}b4cb316e71612d7500508f235ebba148' to '{md5}073e6e856c
e9ecaa369b58cdb47e9ff5'
==> default: Notice: /Stage[main]/Nginx::Config/File[/etc/nginx/conf.stream.d]/ensure: created
==> default: Notice: /Stage[main]/Nginx::Config/File[/etc/nginx/conf.mail.d]/ensure: created
==> default: Notice: /Stage[main]/Nginx::Config/File[/etc/nginx/sites-enabled/default]/ensure: removed
==> default: Notice: /Stage[main]/Omegaup::Scripts/File[/usr/bin/mkhexdirs]/ensure: defined content as '{md5}4823bf83a39fd41544b1aee334a2fd3d'
==> default: Notice: /Stage[main]/Omegaup::Grader/Exec[grade-directory]/returns: executed successfully
==> default: Notice: /Stage[main]/Omegaup::Grader/File[/var/log/omegaup/service.log]/ensure: created
==> default: Notice: /Stage[main]/Omegaup::Grader/File[/etc/systemd/system/omegaup.service]/ensure: defined content as '{md5}731dc048bae8fbd264652dde6cc388e4'
==> default: Notice: /Stage[main]/Omegaup::Grader/File[/var/lib/omegaup/compile]/ensure: created
==> default: Notice: /Stage[main]/Omegaup::Grader/Package[libmysql-java]/ensure: ensure changed 'purged' to 'present'
==> default: Notice: /Stage[main]/Omegaup::Grader/File[/etc/omegaup/grader/omegaup.conf]/ensure: defined content as '{md5}b60cc1aba358413b333cbc65e2f12548'
==> default: Notice: /Stage[main]/Omegaup::Grader/Service[omegaup]/ensure: ensure changed 'stopped' to 'running'
==> default: Notice: /Stage[main]/Omegaup::Grader/File[/var/lib/omegaup/input]/ensure: created
==> default: Notice: /Stage[main]/Apt/File[preferences]/ensure: created
==> default: Notice: /Stage[main]/Omegaup::Database/File[/tmp/omegaup-countries-and-states.sql]/ensure: defined content as '{md5}02cd177578143d2685fe3ebaaaff2e4
d'
==> default: Notice: /Stage[main]/Mysql::Server::Service/File[/var/log/mysql/error.log]/group: group changed 'adm' to 'mysql'
==> default: Notice: /Stage[main]/Mysql::Server::Root_password/Mysql_user[root@localhost]/password_hash: defined 'password_hash' as '*AB1E2A905834AFE20D55068A74
5FF4DC06CF679C'
==> default: Notice: /Stage[main]/Mysql::Server::Root_password/File[/root/.my.cnf]/ensure: defined content as '{md5}3ef753f0dffdeae2945be4867f7b4132'
==> default: Notice: /Stage[main]/Omegaup::Database/Mysql::Db[omegaup]/Mysql_user[omegaup@localhost]/ensure: created
==> default: Notice: /Stage[main]/Mysql::Client::Install/Package[mysql_client]/ensure: ensure changed 'purged' to 'present'
==> default: Notice: /Stage[main]/Omegaup::Database/Mysql::Db[omegaup-test]/Mysql_database[omegaup-test]/ensure: created
==> default: Notice: /Stage[main]/Omegaup::Database/Mysql::Db[omegaup]/Mysql_database[omegaup]/ensure: created
==> default: Notice: /Stage[main]/Omegaup::Database/Mysql::Db[omegaup]/Mysql_grant[omegaup@localhost/omegaup.*]/ensure: created
==> default: Notice: /Stage[main]/Omegaup::Database/Mysql::Db[omegaup]/Exec[omegaup-import]: Triggered 'refresh' from 1 events
==> default: Notice: /Stage[main]/Omegaup::Database/Mysql::Db[omegaup-test]/Mysql_grant[omegaup@localhost/omegaup-test.*]/ensure: created
==> default: Notice: /Stage[main]/Omegaup::Database/Mysql::Db[omegaup-test]/Exec[omegaup-test-import]: Triggered 'refresh' from 1 events
==> default: Notice: /Stage[main]/Omegaup::Developer_environment/Package[phpunit-selenium]/ensure: ensure changed 'purged' to 'present'
==> default: Notice: /Stage[main]/Omegaup::Developer_environment/Package[silversearcher-ag]/ensure: ensure changed 'purged' to 'present'
==> default: Notice: /Stage[main]/Omegaup::Developer_environment/Package[php-codesniffer]/ensure: ensure changed 'purged' to 'present'
==> default: Notice: /Stage[main]/Omegaup::Developer_environment/Package[g++]/ensure: ensure changed 'purged' to 'present'
==> default: Notice: /Stage[main]/Omegaup::Developer_environment/File[/usr/bin/sbt]/ensure: defined content as '{md5}3f09056ffc698790ded8ae4e539039e6'
==> default: Notice: /Stage[main]/Omegaup::Developer_environment/Omegaup::Developer_environment::Remote_file[/usr/bin/sbt-launch.jar]/Exec[wget_/usr/bin/sbt-lau
nch.jar]/returns: executed successfully
==> default: Notice: /Stage[main]/Omegaup::Apt_sources/Apt::Ppa[ppa:omegaup/omegaup]/Exec[add-apt-repository-ppa:omegaup/omegaup]/returns: executed successfully

==> default: Notice: /Stage[main]/Apt::Update/Exec[apt_update]/returns: executed successfully
==> default: Notice: /Stage[main]/Apt::Update/Exec[apt_update]: Triggered 'refresh' from 1 events
==> default: Notice: /Stage[main]/Omegaup::Apt_sources/Apt::Ppa[ppa:omegaup/omegaup]/File[/etc/apt/sources.list.d/omegaup-omegaup-vivid.list]/ensure: created
==> default: Notice: /Stage[main]/Omegaup::Minijail/Package[omegaup-minijail]/ensure: ensure changed 'purged' to 'present'
==> default: Notice: /Stage[main]/Omegaup/Exec[submissions-directory]/returns: executed successfully
==> default: Notice: /Stage[main]/Omegaup/Package[zip]/ensure: ensure changed 'purged' to 'present'
==> default: Notice: /Stage[main]/Omegaup/Package[hhvm]/ensure: ensure changed 'purged' to 'present'
==> default: Notice: /Stage[main]/Omegaup::Developer_environment/File_line[hhvm include_path]/ensure: created
==> default: Notice: /Stage[main]/Omegaup/File[/var/log/omegaup/omegaup.log]/ensure: created
==> default: Notice: /Stage[main]/Omegaup/File[/var/lib/omegaup/problems]/ensure: created
==> default: Notice: /Stage[main]/Omegaup/File[/var/lib/omegaup/problems.git]/ensure: created
==> default: Notice: /Stage[main]/Omegaup/Service[hhvm]/enable: enable changed 'false' to 'true'
==> default: Notice: /Stage[main]/Omegaup/File[/opt/omegaup]/ensure: created
==> default: Notice: /Stage[main]/Omegaup/Vcsrepo[/opt/omegaup]/ensure: Creating repository from present
==> default: Notice: /Stage[main]/Omegaup/File[/opt/omegaup/frontend/www/img]: Dependency Vcsrepo[/opt/omegaup] has failures: true
==> default: Notice: /Stage[main]/Omegaup/File[/var/www/omegaup.com]: Dependency Vcsrepo[/opt/omegaup] has failures: true
==> default: Error: Execution of 'git submodule update --init --recursive' returned 1: Submodule 'backend' (https://github.com/omegaup/backend.git) registered f
or path 'backend'
==> default: Submodule 'frontend/server/libs/adodb' (https://github.com/ADOdb/ADOdb.git) registered for path 'frontend/server/libs/adodb'
==> default: Submodule 'frontend/server/libs/google-api-php-client' (https://github.com/google/google-api-php-client) registered for path 'frontend/server/libs/
google-api-php-client'
==> default: Submodule 'frontend/server/libs/log4php' (https://github.com/omegaup/logging-log4php.git) registered for path 'frontend/server/libs/log4php'
==> default: Submodule 'frontend/www/js/mathjax' (https://github.com/mathjax/MathJax.git) registered for path 'frontend/www/js/mathjax'
==> default: Submodule 'frontend/www/js/pagedown' (https://github.com/omegaup/pagedown.git) registered for path 'frontend/www/js/pagedown'
==> default: Error: /Stage[main]/Omegaup/Vcsrepo[/opt/omegaup]/ensure: change from absent to present failed: Execution of 'git submodule update --init --recursi
ve' returned 1: Submodule 'backend' (https://github.com/omegaup/backend.git) registered for path 'backend'
==> default: Submodule 'frontend/server/libs/adodb' (https://github.com/ADOdb/ADOdb.git) registered for path 'frontend/server/libs/adodb'
==> default: Submodule 'frontend/server/libs/google-api-php-client' (https://github.com/google/google-api-php-client) registered for path 'frontend/server/libs/
google-api-php-client'
==> default: Submodule 'frontend/server/libs/log4php' (https://github.com/omegaup/logging-log4php.git) registered for path 'frontend/server/libs/log4php'
==> default: Submodule 'frontend/www/js/mathjax' (https://github.com/mathjax/MathJax.git) registered for path 'frontend/www/js/mathjax'
==> default: Submodule 'frontend/www/js/pagedown' (https://github.com/omegaup/pagedown.git) registered for path 'frontend/www/js/pagedown'
==> default: Warning: /Stage[main]/Omegaup/File[/opt/omegaup/frontend/www/img]: Skipping because of failed dependencies
==> default: Warning: /Stage[main]/Omegaup/File[/var/www/omegaup.com]: Skipping because of failed dependencies
==> default: Notice: /Stage[main]/Omegaup/File[/opt/omegaup/frontend/www/templates]: Dependency Vcsrepo[/opt/omegaup] has failures: true
==> default: Warning: /Stage[main]/Omegaup/File[/opt/omegaup/frontend/www/templates]: Skipping because of failed dependencies
==> default: Notice: /Stage[main]/Omegaup/Omegaup::Config_php[/opt/omegaup/frontend/server/config.php]/File[/opt/omegaup/frontend/server/config.php]: Dependency
 Vcsrepo[/opt/omegaup] has failures: true
==> default: Warning: /Stage[main]/Omegaup/Omegaup::Config_php[/opt/omegaup/frontend/server/config.php]/File[/opt/omegaup/frontend/server/config.php]: Skipping
because of failed dependencies
==> default: Notice: /Stage[main]/Omegaup::Developer_environment/File[/opt/omegaup/frontend/tests/controllers/submissions]: Dependency Vcsrepo[/opt/omegaup] has
 failures: true
==> default: Warning: /Stage[main]/Omegaup::Developer_environment/File[/opt/omegaup/frontend/tests/controllers/submissions]: Skipping because of failed dependen
cies
==> default: Notice: /Stage[main]/Omegaup::Developer_environment/File[/opt/omegaup/frontend/tests/controllers/omegaup.log]: Dependency Vcsrepo[/opt/omegaup] has
 failures: true
==> default: Warning: /Stage[main]/Omegaup::Developer_environment/File[/opt/omegaup/frontend/tests/controllers/omegaup.log]: Skipping because of failed dependen
cies
==> default: Notice: /Stage[main]/Omegaup::Developer_environment/File[/opt/omegaup/frontend/tests/controllers/problems]: Dependency Vcsrepo[/opt/omegaup] has fa
ilures: true
==> default: Warning: /Stage[main]/Omegaup::Developer_environment/File[/opt/omegaup/frontend/tests/controllers/problems]: Skipping because of failed dependencie
s
==> default: Notice: /Stage[main]/Omegaup/Nginx::Resource::Vhost[omegaup]/Concat[/etc/nginx/sites-available/omegaup.conf]/File[/etc/nginx/sites-available/omegau
p.conf]/ensure: defined content as '{md5}8630eaf8ea55fe54c6ff6a9ef3cd9714'
==> default: Notice: /Stage[main]/Omegaup/Nginx::Resource::Vhost[omegaup]/File[omegaup.conf symlink]/ensure: created
==> default: Notice: /Stage[main]/Omegaup::Developer_environment/Omegaup::Config_php[/opt/omegaup/frontend/tests/test_config.php]/File[/opt/omegaup/frontend/tes
ts/test_config.php]: Dependency Vcsrepo[/opt/omegaup] has failures: true
==> default: Warning: /Stage[main]/Omegaup::Developer_environment/Omegaup::Config_php[/opt/omegaup/frontend/tests/test_config.php]/File[/opt/omegaup/frontend/te
sts/test_config.php]: Skipping because of failed dependencies
==> default: Notice: /Stage[main]/Omegaup/Nginx::Resource::Location[php]/File[/etc/nginx/fastcgi_params]/content: content changed '{md5}f597fb54a6fa1c9a9678dd3a
e377d385' to '{md5}9d2f3b886473a8d8c9f605facc7d20fa'
==> default: Notice: /Stage[main]/Omegaup/Nginx::Resource::Location[php]/File[/etc/nginx/fastcgi_params]/mode: mode changed '0644' to '0770'
==> default: Notice: /Stage[main]/Nginx::Service/Service[nginx]: Triggered 'refresh' from 1 events
==> default: Notice: /Stage[main]/Omegaup/File[/opt/omegaup/.git/hooks/pre-push]: Dependency Vcsrepo[/opt/omegaup] has failures: true
==> default: Warning: /Stage[main]/Omegaup/File[/opt/omegaup/.git/hooks/pre-push]: Skipping because of failed dependencies
==> default: Notice: Finished catalog run in 614.88 seconds
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.`

**Comment by samdsmx** [comment]
Nuevo log... aun con errores.
[log.txt](https://github.com/omegaup/deploy/files/177266/log.txt)

**Comment by lhchavez** [comment]
Según esto con https://github.com/omegaup/omegaup/commit/2deae03cc44618704d48e232fde4e40eaf952b0b quedó arreglado.
